version: '3'

services:
  pokemon-showdown:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    # volumes:
    #   - ${LOCAL_APP_PATH}:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
