version: '3'

services:
  pokemon-showdown:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
