version: '3'

services:
  pokemon-showdown:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./Users/koji/data/pokemon/app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
